### ISSUE TITLE
Add ARM

### ISSUE THREAD

**Issue by vitaly-zdanevich** [maxday/lambda-perf#13]

**Comment by maxday** [comment]
Hey 👋 @vitaly-zdanevich 
It's now live! https://maxday.github.io/lambda-perf/

**Comment by vitaly-zdanevich** [comment]
Hi, thanks, but not for Go?

![image](https://user-images.githubusercontent.com/3514015/233933026-b70f8d7e-680b-4e8f-8bbb-40cedf08ff2e.png)

**Comment by maxday** [comment]
good catch! it's now live
