### ISSUE TITLE
.NET 7 Native AOT

### ISSUE THREAD

**Issue by sergey-tihon** [maxday/lambda-perf#2]
Would be interesting to see results with .NET 7 Lambda functions with Native AOT compilation (also with `provided.al2` runtime)
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/build-dotnet7.html

to demystify the believe in `x10` performance boost - https://twitter.com/maloo321/status/1619788488316170240

**Comment by RichiCoder1** [comment]
Yah (as a .NET dev), I don't expect this will be a x10. More likely it will be in line with or lower than dotnetcore31. Still a very good datapoint however.

**Comment by maxday** [comment]
sure good idea! I'll have a look this week

**Comment by maxday** [comment]
Thanks a lot @RichiCoder1 it's live!
<img width="834" alt="Screenshot 2023-02-10 at 10 24 55 AM" src="https://user-images.githubusercontent.com/864493/218129493-2180a075-ba01-4cfc-a419-3b9e2b8868d3.png">

**Comment by RichiCoder1** [comment]
That's awesome! Not rust, but nice to see the hard numbers 🐶
