### ISSUE TITLE
dedup runtimes array

### ISSUE THREAD

**Issue by maxday** [maxday/lambda-perf#33]
for now the runtimes array is at 3 different places, let's refactor it at one place :)

**Comment by kidylee** [comment]
It would be great if all the components are metadata driven.

Let's say we will have a yaml which contains runtime definition and corresponding parameters to each runtime, then upload this metadata.yaml to S3 alone with other runtime binaries. Then deployer, trigger and report read metadata from S3 and act as it was defined in this yaml file.

**Comment by maxday** [comment]
exact! I've just implemented it! #65
