### ISSUE TITLE
Add Bun Lambda To The Benchmark Suite

### ISSUE THREAD

**Issue by shollington-rbi** [maxday/lambda-perf#602]
Given all the recent hype around the launch of [bun v1](https://bun.sh/blog/bun-v1.0), it would be awesome if the official bun Lambda runtime could be added to the benchmark suite:

* https://github.com/oven-sh/bun/tree/main/packages/bun-lambda
* https://medium.com/@mitchellkossoris/serverless-bun-vs-node-benchmarking-on-aws-lambda-ecd4fe7c2fc2

This is particularly interesting as Bun is supposed to index highly in start-up speed, but from the blog post above, it appears that the lambda cold start time is currently slower than Node.

**Comment by maxday** [comment]
Closing this as it's now released (for x64)
