### ISSUE TITLE
Java 11 Corretto with SnapStart

### ISSUE THREAD

**Issue by astuyve** [maxday/lambda-perf#7]
I think it would be just the coolest thing if someone would contribute a function running Java 11 Corretto with and without SnapStart.

Love this project!! 😍

**Comment by maxday** [comment]
Hey @astuyve 
Thanks to @kidylee and #12 -> Java 11 with snapstart is now live!

<img width="388" alt="Screenshot 2023-02-13 at 1 44 30 AM" src="https://user-images.githubusercontent.com/864493/218389302-09801962-2fdc-4fa1-a9f8-97404a39f77a.png">
