### ISSUE TITLE
Add AWS LLRT runtime

### ISSUE THREAD

**Issue by o-alexandrov** [maxday/lambda-perf#991]
[LLRT (Low Latency Runtime): Amazon's New JS Runtime](https://javascriptweekly.com/link/151396/463fd4a36a) — Amazon has open sourced a runtime entirely focused on fast startups – something that’s useful for ephemeral use cases like serverless (*cough* AWS Lambda). It uses Fabrice Bellard’s [QuickJS](https://javascriptweekly.com/link/151397/463fd4a36a) as the underlying engine, so has almost full ES2023 spec support out of the box.

**Comment by maxday** [comment]
hey @o-alexandrov, this runtime has already been added :)
see: https://github.com/maxday/lambda-perf/pull/959
